"use client";
import{useMemo,useRef,useState}from"react";import{Upload,FileText,Ruler,ScanLine,CheckCircle2,Plus}from"lucide-react";
const items=[["W01","Internal partition","13.88 m²","K10/115","HIGH"],["W02","Acoustic partition","18.42 m²","K10/125","HIGH"],["W03","WC partition","6.20 m²","K10/135","MEDIUM"],["F01","Porcelain floor tile","28.40 m²","M40/110","HIGH"]];
export default function Home(){const[sel,setSel]=useState("W01");const[calibrated,setCalibrated]=useState(false);const footprint=useMemo(()=>9*5.4,[]);const[tool,setTool]=useState<"length"|"area"|"count"|"calibrate">("calibrate");const[mmPerPct,setMmPerPct]=useState(0);const[aiObjects,setAiObjects]=useState(false);const[pts,setPts]=useState<{x:number,y:number}[]>([]);const board=useRef<HTMLDivElement>(null);const addPoint=(e:React.MouseEvent)=>{if((!calibrated&&tool!=="calibrate")||!board.current)return;const r=board.current.getBoundingClientRect();const q={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};if(tool==="calibrate"){setPts(p=>{const n=[...p,q].slice(-2);if(n.length===2){const d=Math.hypot(n[1].x-n[0].x,n[1].y-n[0].y);const known=Number(prompt("Known distance between these points (mm)","9000"));if(known>0&&d>0){setMmPerPct(known/d);setCalibrated(true)}}return n})}else setPts(p=>[...p,q])};const reset=()=>setPts([]);const qty=useMemo(()=>{if(tool==="calibrate")return 0;if(tool==="count")return pts.length;if(pts.length<2)return 0;if(tool==="length"){let n=0;for(let i=1;i<pts.length;i++)n+=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);return n*mmPerPct/1000}if(pts.length<3)return 0;let a=0;for(let i=0;i<pts.length;i++){const j=(i+1)%pts.length;a+=pts[i].x*pts[j].y-pts[j].x*pts[i].y}return Math.abs(a/2)*mmPerPct*mmPerPct/1e6},[pts,tool,mmPerPct]);
return <main><header><b><i>HX</i> TAKEOFF</b><span>HX TEST PROJECT 001 · Intelligence benchmark</span><em>DH</em></header><nav>Projects　 <strong>Drawings</strong>　 Documents　 Take-off　 BOQ</nav>
<section className="hero"><div><small>MEASUREMENT ENGINE · TEST 001</small><h1>Drawing intelligence workspace.</h1><p>Known drawing dimensions are used to calibrate geometry before AI interpretation and quantity approval.</p></div><button><Plus size={17}/> New take-off</button></section>
<section className="steps">{[[Upload,"1. Drawing","A-101 · Rev P01"],[Ruler,"2. Calibrate",calibrated?"9,000 × 5,400mm ✓":"Use known dimensions"],[ScanLine,"3. Measure","Deterministic geometry"],[CheckCircle2,"4. Validate","Benchmark 48.60m²"]].map(([I,a,b]:any,i)=><article key={i}><I/><b>{a}</b><span>{b}</span></article>)}</section>
<section className="work"><aside><h5>DRAWINGS</h5><div className="doc on"><FileText/> A-101 Ground Floor Plan</div><h5>DOCUMENTS</h5><div className="doc"><FileText/> Test Architectural Specification</div><button className="upload">＋ Upload documents</button><h5>AI DRAWING READ</h5><button className="upload" onClick={()=>setAiObjects(true)}>✦ Analyse test drawing</button>{aiObjects&&<p style={{fontSize:12,lineHeight:1.5}}>✓ 5 rooms detected<br/>✓ 3 partition types detected<br/>✓ Drawing A-101 / P01 recognised<br/>✓ 9000 × 5400 dimension evidence found</p>}<h5>CALIBRATION</h5><p style={{fontSize:12,lineHeight:1.5}}>Independent dimensions: 9,000mm × 5,400mm.</p><button className="upload" onClick={()=>{setTool("calibrate");setPts([]);setCalibrated(false)}}>{calibrated?`✓ Scale ${mmPerPct.toFixed(1)} mm/unit`:"Start 2-point calibration"}</button></aside>
<div className="viewer"><div className="bar">A-101 · Ground Floor Plan <span>Scale 1:50 · Rev P01</span></div><div style={{position:"relative",background:"#fff",minHeight:520,display:"grid",placeItems:"center",overflow:"auto"}}><img src="/test-project-001.svg" alt="HX Test Project 001 ground floor plan" style={{width:"100%",maxWidth:900,height:"auto"}}/>{calibrated&&<div style={{position:"absolute",left:"13%",top:"14%",right:"14%",bottom:"18%",border:"3px solid #c6a24b",pointerEvents:"none"}}/>}</div></div>
<aside className="take"><h5>TAKE-OFF EVIDENCE　 <mark>{calibrated?"SCALE VALID":"REVIEW"}</mark></h5>{aiObjects&&<div className="item picked"><div><b>AI drawing interpretation</b><small>Geometry + tags + dimension evidence</small></div><strong>REVIEW</strong></div>}<div className="item picked"><div><b>Benchmark footprint</b><small>9.000m × 5.400m · Drawing dimensions</small></div><strong>{footprint.toFixed(2)} m²</strong></div>{items.map(x=><div key={x[0]} onClick={()=>setSel(x[0])} className={"item "+(sel===x[0]?"picked":"")}><div><b>{x[0]} · {x[1]}</b><small>Spec {x[3]} · Evidence {x[4]}</small></div><strong>{x[2]}</strong></div>)}<footer><button>Reject</button><button>Amend</button><button className="approve">Approve</button></footer></aside></section></main>}